config/routes.rb
Rails.application.routes.draw do
  get 'report/view'

  resources :order_lines

  resources :products

  resources :placed_orders

  resources :customers

  root 'report#view'

end

app/models/placed_order.rb
class PlacedOrder < ActiveRecord::Base
  belongs_to :customer
  has_many :order_lines
end

app/controllers/placed_orders_controller.rb
class PlacedOrdersController < ApplicationController
  before_action :set_placed_order, only: [:show, :edit, :update, :destroy]

  # GET /placed_orders
  # GET /placed_orders.json
  def index
    @placed_orders = PlacedOrder.all
  end

  # GET /placed_orders/1
  # GET /placed_orders/1.json
  def show
  end

  # GET /placed_orders/new
  def new
    @placed_order = PlacedOrder.new
  end

  # GET /placed_orders/1/edit
  def edit
  end

  # POST /placed_orders
  # POST /placed_orders.json
  def create
    @placed_order = PlacedOrder.new(placed_order_params)

    respond_to do |format|
      if @placed_order.save
        format.html { redirect_to @placed_order, notice: 'Placed order was successfully created.' }
        format.json { render :show, status: :created, location: @placed_order }
      else
        format.html { render :new }
        format.json { render json: @placed_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /placed_orders/1
  # PATCH/PUT /placed_orders/1.json
  def update
    respond_to do |format|
      if @placed_order.update(placed_order_params)
        format.html { redirect_to @placed_order, notice: 'Placed order was successfully updated.' }
        format.json { render :show, status: :ok, location: @placed_order }
      else
        format.html { render :edit }
        format.json { render json: @placed_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /placed_orders/1
  # DELETE /placed_orders/1.json
  def destroy
    @placed_order.destroy
    respond_to do |format|
      format.html { redirect_to placed_orders_url, notice: 'Placed order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_placed_order
      @placed_order = PlacedOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def placed_order_params
      params.require(:placed_order).permit(:time_placed, :customer_id)
    end
end

app/helpers/placed_orders_helper.rb
module PlacedOrdersHelper
end

app/views/placed_orders/_form.html.erb
<%= form_for(@placed_order) do |f| %>
  <% if @placed_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@placed_order.errors.count, "error") %> prohibited this placed_order from being saved:</h2>

      <ul>
      <% @placed_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_placed %><br>
    <%= f.datetime_select :time_placed %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/placed_orders/edit.html.erb
<h1>Editing placed_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @placed_order %> |
<%= link_to 'Back', placed_orders_path %>

app/views/placed_orders/index.html.erb
<h1>Listing placed_orders</h1>

<table>
  <thead>
    <tr>
      <th>Time placed</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @placed_orders.each do |placed_order| %>
      <tr>
        <td><%= placed_order.time_placed %></td>
        <td><%= placed_order.customer %></td>
        <td><%= link_to 'Show', placed_order %></td>
        <td><%= link_to 'Edit', edit_placed_order_path(placed_order) %></td>
        <td><%= link_to 'Destroy', placed_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Placed order', new_placed_order_path %>

app/views/placed_orders/new.html.erb
<h1>New placed_order</h1>

<%= render 'form' %>

<%= link_to 'Back', placed_orders_path %>

app/views/placed_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time placed:</strong>
  <%= @placed_order.time_placed %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @placed_order.customer %>
</p>

<%= link_to 'Edit', edit_placed_order_path(@placed_order) %> |
<%= link_to 'Back', placed_orders_path %>