config/routes.rb
Rails.application.routes.draw do
  get 'report/view'

  resources :order_lines

  resources :products

  resources :placed_orders

  resources :customers

  root 'report#view'

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :product
  belongs_to :placed_order
  validates :amount, presence: true
  validates :amount, numericality: {greater_than: 0}
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  before_action :set_order_line, only: [:show, :edit, :update, :destroy]

  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
  end

  # GET /order_lines/new
  def new
    @order_line = OrderLine.new
  end

  # GET /order_lines/1/edit
  def edit
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(order_line_params)

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render :show, status: :created, location: @order_line }
      else
        format.html { render :new }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_lines/1
  # PATCH/PUT /order_lines/1.json
  def update
    respond_to do |format|
      if @order_line.update(order_line_params)
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line }
      else
        format.html { render :edit }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line.destroy
    respond_to do |format|
      format.html { redirect_to order_lines_url, notice: 'Order line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_params
      params.require(:order_line).permit(:amount, :product_id, :placed_order_id)
    end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.erb
<%= form_for(@order_line) do |f| %>
  <% if @order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
      <% @order_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :placed_order_id %><br>
    <%= f.text_field :placed_order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Editing order_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<h1>Listing order_lines</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Product</th>
      <th>Placed order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_lines.each do |order_line| %>
      <tr>
        <td><%= order_line.amount %></td>
        <td><%= order_line.product %></td>
        <td><%= order_line.placed_order %></td>
        <td><%= link_to 'Show', order_line %></td>
        <td><%= link_to 'Edit', edit_order_line_path(order_line) %></td>
        <td><%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order line', new_order_line_path %>

app/views/order_lines/new.html.erb
<h1>New order_line</h1>

<%= render 'form' %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @order_line.amount %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_line.product %>
</p>

<p>
  <strong>Placed order:</strong>
  <%= @order_line.placed_order %>
</p>

<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>